permalink: pretty
markdown: redcarpet
pygments: true

exclude: ["CNAME", "README", "Gemfile", "Gemfile.lock", "Procfile", "config.rb", "sass"]

title: Austin.RB
url: http://austinrb.org
email: ttyrrell+austinrb@gmail.com
meeting:
  when:
    date: "Wednesday, May 9"
    time: "7:30-9:30PM"
    url: "http://plancast.com/p/ba7e"
  where:
    location: "CoSpace"
    url: "http://cospaceatx.com/"
