permalink: pretty
markdown: redcarpet
pygments: true

exclude: ["CNAME", "README", "Gemfile", "Gemfile.lock", "Procfile", "config.rb", "sass"]

title: Austin.RB
url: http://austinrb.org
email: ttyrrell+austinrb@gmail.com
meeting:
  when:
    date: "Wednesday, September 12"
    time: "7:30-9:30pm"
    url: "http://plancast.com/p/cryp"
  where:
    location: "Capital Factory"
    url: "http://www.capitalfactory.com/"
